using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WebApp.Migrations
{
    /// <inheritdoc />
    public partial class BumpIdentityStart : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
        DECLARE
         v_next NUMBER;
        BEGIN
         SELECT NVL(MAX(ID_BRINQUEDO),0)+1 INTO v_next FROM TDS_TB_BRINQUEDOS;
         EXECUTE IMMEDIATE
          'ALTER TABLE TDS_TB_BRINQUEDOS MODIFY (ID_BRINQUEDO GENERATED BY DEFAULT AS IDENTITY (START WITH '||v_next||'))';
        END;");

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
