// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250904003826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.Brinquedo", b =>
                {
                    b.Property<int>("IdBrinquedo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_BRINQUEDO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBrinquedo"));

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<string>("NomeBrinquedo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME_BRINQUEDO");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECO");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TAMANHO");

                    b.Property<string>("TipoBrinquedo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("TIPO_BRINQUEDO");

                    b.HasKey("IdBrinquedo");

                    b.ToTable("TDS_TB_BRINQUEDOS");

                    b.HasData(
                        new
                        {
                            IdBrinquedo = 1,
                            Classificacao = "Livre",
                            NomeBrinquedo = "Carrinho",
                            Preco = 29.90m,
                            Tamanho = "Pequeno",
                            TipoBrinquedo = "Veículo"
                        },
                        new
                        {
                            IdBrinquedo = 2,
                            Classificacao = "Livre",
                            NomeBrinquedo = "Boneca",
                            Preco = 59.90m,
                            Tamanho = "Médio",
                            TipoBrinquedo = "Boneca"
                        },
                        new
                        {
                            IdBrinquedo = 3,
                            Classificacao = "+6",
                            NomeBrinquedo = "Quebra-cabeça 100 peças",
                            Preco = 39.90m,
                            Tamanho = "Médio",
                            TipoBrinquedo = "Puzzle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
